version: '2'

services: 
  pymc:
    image: u03013112/pymc:v1
    container_name: 'pymc'
    tty: true
    volumes:
      - ../../:/src:cached
    working_dir: /src/
    network_mode: host
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"